#!/bin/bash

# sgc - sgl
for i in {e,i}
do
#    screen -dmS sg$i sg_format --format --size=512 /dev/sg$i
#    tmux new-session -d -s sg$i "sg_format --format --size=512 /dev/sg$i"
#    tmux new-session -d -s sd$i 'sg_format --format --size512 /dev/sd$i'
    tmux new -s sd$i -d \; setw remain-on-exit on \; respawnw -k sg_format --format --quick /dev/sd$i
    echo "Starting format of sd$i"
done
